name: 'Code Structure Evaluator'
description: 'Evaluates code structure using LLMs and provides a score with explanation'
author: 'Krishna Kumar'
inputs:
  api-key:
    description: 'API key for the LLM service'
    required: true
  rubric:
    description: 'Path to a custom rubric YAML file (optional)'
    required: false
    default: ''
outputs:
  score:
    description: 'Total score from the evaluation'
  explanation:
    description: 'Detailed explanation of the evaluation'
runs:
  using: 'composite'
  steps:
    - name: Install Dependencies
      shell: bash
      run: |
        cd ${{ github.action_path }}
        npm install
    - name: Run Action
      shell: node16
      run: ${{ github.action_path }}/index.js
      env:
        INPUT_API_KEY: ${{ inputs.api-key }}
        INPUT_RUBRIC: ${{ inputs.rubric }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
        GITHUB_OUTPUT: ${{ github.output }}
branding:
  icon: 'check-square'
  color: 'blue'
